version: "3.3"
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile.app
        volumes:
            - ./results:/app/files

    nginx:
        build: 
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - 8080:80


